aws:
  s3:
    mock: false
spring:
  datasource:
    url: jdbc:postgresql://awseb-e-icxztsfwdv-stack-awsebrdsdatabase-nmezyximduvr.c3dalozr1mze.us-west-2.rds.amazonaws.com:5432/ebdb
    username: amigoscode
    password: password